import CustomError from "./custom-error";

class InternalErrorException extends CustomError {
    constructor(message: string = 'Erro ao utilizar o servi√ßo. Tente novamente!'){
        super(message, 500)
    }
}

export default InternalErrorException;